import { CustomerSlate, ExtractedEntities } from '../../types/nlu';
import { DEFAULT_TENANT_ID } from '../../config/tenant';
import { GOLD_FEW_SHOT_EXEMPLARS } from './gold-few-shot-exemplars';

export interface FewShotExemplar {
  id: string;
  tenantId?: string;
  scenario: string;
  tags: string[];
  customerMessage: string;
  idealResponse: string;
  isActive?: boolean;
  sortOrder?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

/**
 * Bank Percakapan Ideal Bawaan Sistem (Default System Exemplars).
 * Selalu tersedia sebagai fallback jika database offline atau tabel kosong.
 * CATATAN: id statis ini HANYA untuk representasi in-memory/fallback.
 * Record riil di database memakai UUID autogenerated (lihat resetToDefaults
 * yang mengembalikan id asli dari database, bukan id statis ini).
 */
export const DEFAULT_FEW_SHOT_EXEMPLARS: FewShotExemplar[] = [
  {
    id: 'symptom_flu_consultation',
    scenario: 'Pasien berkonsultasi keluhan batuk / pilek / flu / grok-grok pada bayi',
    tags: ['consult_symptom', 'flu', 'batuk', 'pilek', 'grok', 'gejala'],
    customerMessage: 'Anak saya usia 3 bulan lagi grok-grok dan pilek bun, ada pijatnya gak ya?',
    idealResponse:
      'Iya Bunda, untuk membantu melegakan pernapasan dan ketidaknyamanan si kecil, kami ada layanan *Pijat Bayi Pulih Ceria* yang dikombinasikan dengan teknik akupresur dan aromaterapi khusus flu/batuk pilek yaa 😊 Rencana mau kami bantu jadwalkan di hari apa ya Bunda? 🤗',
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'schedule_inquiry_anti_affirmation',
    scenario: 'Pasien menanyakan ketersediaan jadwal di hari tertentu (Anti-Afirmasi Jadwal)',
    tags: ['ask_schedule', 'schedule', 'jadwal', 'sabtu', 'minggu', 'besok'],
    customerMessage: 'Hari Sabtu ini bu bidan bisa datang ke rumah?',
    idealResponse:
      'Untuk ketersediaan jadwal di hari Sabtu, akan kami bantu cekkan ketersediaan jadwal Bidan yang ready terlebih dahulu ya Bunda 😊 Nanti jadwal hari dan jam kunjungannya akan kami infokan setelah Admin CS kami cekkan ya 🙏',
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'price_inquiry',
    scenario: 'Pasien menanyakan tarif/harga layanan',
    tags: ['ask_price', 'price', 'harga', 'tarif', 'biaya'],
    customerMessage: 'Untuk tarif pijat batuk pilek kena berapa ya bun?',
    idealResponse:
      'Untuk layanan *Pijat Bayi Pulih Ceria*, tarif promonya saat ini *Rp 70.000* (durasi ±40 menit) ya Bunda 😊 Mau kami bantu cekkan ketersediaan jadwal Bidan untuk kunjungan ke rumah?',
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'payment_method_inquiry',
    scenario: 'Pasien menanyakan metode pembayaran (Transfer / QRIS / Cash)',
    tags: ['payment', 'qris', 'transfer', 'cash'],
    customerMessage: 'Pembayarannya bisa transfer atau harus cash kak?',
    idealResponse:
      'Untuk pembayaran sangat fleksibel ya Bunda, bisa melalui Transfer Bank (BCA, Mandiri, BRI), QRIS Universal, ataupun Tunai (Cash) setelah treatment selesai dilakukan 😊 Mau kami bantu cekkan jadwal Bidan?',
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 'location_ongkir_confirmation',
    scenario: 'Customer menyebutkan lokasi/kecamatan untuk cek layanan & ongkir',
    tags: ['lokasi', 'domisili', 'alamat', 'kecamatan', 'kec', 'kelurahan', 'kel', 'desa', 'perum', 'sidoarjo', 'surabaya', 'ongkir', 'jarak'],
    customerMessage: 'Saya di Balongdowo Candi Sidoarjo kak',
    idealResponse:
      'Baik Bunda 😊 Jika dilihat dari Waru jaraknya kurang lebih 23 km dengan ongkir promo Rp 25.000 yaa. Rencana mau ambil perawatan apa untuk si kecil atau Bunda? 🤗',
    isActive: true,
    sortOrder: 33,
  },
  {
    id: 'schedule_check_admin_handoff_sync',
    scenario: 'Customer bertanya ketersediaan jadwal besok saat lokasi sudah diketahui — cekkan Admin, tanya perkiraan jam, tanpa tanya alamat',
    tags: ['ask_schedule', 'jadwal', 'hari', 'besok', 'cek', 'ketersediaan', 'treatment', 'admin', 'jam'],
    customerMessage: 'Treatment nya semisal besok apa bisa ya bu ?',
    idealResponse:
      'Untuk ketersediaan jadwal di hari besok, akan kami bantu cekkan ketersediaan jadwal Bidan kami yang ready terlebih dahulu ya Bunda 😊🙏 Mau kami bantu catatkan untuk perkiraan jamnya (pagi atau siang), Bunda? 🤗',
    isActive: true,
    sortOrder: 34,
  },
  {
    id: 'maternal_lactation_inquiry',
    scenario: 'Pasien menanyakan pijat laktasi / oksitosin untuk Ibu Menyusui',
    tags: ['laktasi', 'oksitosin', 'ibu', 'moms'],
    customerMessage: 'Pijat oksitosin itu untuk apa ya bun? Bisa buat lancarin ASI?',
    idealResponse:
      'Benar sekali Bunda 😊 *Pijat Oksitosin* khusus untuk Bunda menyusui/nifas guna merangsang hormon oksitosin alami, membantu melancarkan aliran ASI, serta merilekskan otot punggung dan leher yang tegang. Rencana mau kami bantu jadwalkan di hari apa ya Bunda? 🤗',
    isActive: true,
    sortOrder: 5,
  },
  {
    id: 'post_delivery_treatment_continuation',
    scenario: 'Customer memilih/menentukan treatment (Anti-Penjelasan Ulang & Langsung Tanya Hari)',
    tags: ['follow_up', 'after_ongkir', 'select_treatment', 'massage biasa', 'pijat biasa'],
    customerMessage: 'Massage biasa',
    idealResponse:
      'Baik Bunda, untuk *Pijat Bayi Ceria* rencana mau kami bantu jadwalkan di hari apa ya Bunda? 🙏😊',
    isActive: true,
    sortOrder: 6,
  },
  {
    id: 'symptom_followup_no_cta',
    scenario: 'Pasien berkonsultasi gejala lanjutan atau respon penenang (Pacing Empati / Tanpa Todong CTA Jadwal)',
    tags: ['consult_symptom', 'followup', 'grok', 'gejala', 'lendir', 'pilek', 'bunyi', 'basah'],
    customerMessage: 'Nggk mbeler tp kyk cuman kyk basah trus kdng suka bunyi grr grr',
    idealResponse:
      'Iya Bunda, bunyi grok-grok pada si kecil wajar terjadi karena saluran napas bayi masih sangat sempit, sehingga sedikit lendir saja bisa menimbulkan bunyi saat bernapas 😊 Teknik akupresur dan pijat relaksasi di *Pijat Bayi Pulih Ceria* memang dirancang untuk membantu melegakan pernapasan dan mengencerkan lendir tersebut agar si kecil bisa bernapas lebih lega dan tidur pulas. Semoga si kecil selalu sehat dan nyaman yaa Bunda ✨',
    isActive: true,
    sortOrder: 7,
  },
  // =========================================================================
  // KOLEKSI EMAS (25 contoh master Bidan Yusi dari 532 dialog riil) — lihat
  // ./gold-few-shot-exemplars.ts. Ditambahkan di belakang 7 SOP inti agar
  // instalasi baru / reset SOP langsung mendapat bank contoh yang lengkap.
  // =========================================================================
  ...GOLD_FEW_SHOT_EXEMPLARS,
];

// In-Memory dynamic cache per-tenant (0-latency runtime access)
const tenantExemplarsCache: Map<string, FewShotExemplar[]> = new Map();
// Tenant yang sudah pernah dipastikan "sengaja kosong" oleh admin (state persisten runtime)
// sehingga getAllExemplars TIDAK otomatis me-resurrect default exemplars.
const tenantEmptyStateCache: Map<string, boolean> = new Map();

const mapRowToExemplar = (r: any): FewShotExemplar => ({
  id: r.id,
  tenantId: r.tenant_id,
  scenario: r.scenario,
  tags: r.tags || [],
  customerMessage: r.customer_message,
  idealResponse: r.ideal_response,
  isActive: r.is_active,
  sortOrder: r.sort_order,
  createdAt: r.created_at,
  updatedAt: r.updated_at,
});

/** Escape karakter regex khusus agar aman dipakai di RegExp. */
const escapeRegex = (s: string): string => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/** True bila tag muncul sebagai kata utuh (bukan sub-kata) di dalam teks. */
const isWordTagMatch = (textLower: string, tag: string): boolean => {
  const t = tag.toLowerCase();
  if (!t) return false;
  const escaped = escapeRegex(t);
  return new RegExp(`(?:^|[^a-z0-9])${escaped}(?:$|[^a-z0-9])`, 'i').test(textLower);
};

/**
 * Himpunan tag intent yang memicu prioritas skor tambahan (+5/+2)
 * pada selectRelevantExemplars. Berbasis TAG (bukan id hardcode) sehingga
 * exemplar kustom buatan admin ikut diprioritaskan secara dinamis.
 * Default fallback bila Tenant.settings belum dikonfigurasi.
 */
const DEFAULT_PRIORITY_TAG_GROUPS: Record<string, string[]> = {
  schedule: ['ask_schedule', 'schedule', 'jadwal', 'hari'],
  price: ['ask_price', 'price', 'harga', 'tarif', 'biaya', 'ongkir'],
  symptom: ['consult_symptom', 'symptom', 'flu', 'batuk', 'pilek', 'grok', 'gejala', 'lendir'],
  treatment_continuation: ['follow_up', 'after_ongkir', 'select_treatment'],
  location: ['lokasi', 'domisili', 'alamat', 'ongkir', 'jarak', 'kecamatan', 'kec', 'kelurahan', 'kel', 'desa', 'perum', 'sidoarjo', 'surabaya'],
};

const DEFAULT_DOMAIN_GENERIC_WORDS = new Set(['bayi', 'moms', 'spa', 'anak', 'ibu']);

// Tenant-awareOverrides (diisi via DB Tenant.settings.priorityTagGroups / genericWords)
const tenantPriorityGroupsCache = new Map<string, Record<string, string[]>>();
const tenantGenericWordsCache = new Map<string, Set<string>>();

/** Load override dari Tenant.settings (preferences) — fallback ke default bila belum ada */
async function loadTenantFewShotConfig(tenantId: string): Promise<void> {
  try {
    const { prisma } = await import('../../db/client');
    const tenant = await (prisma as any).tenant.findUnique({ where: { id: tenantId }, select: { settings: true } });
    const settings: any = tenant?.settings || {};
    if (settings.priorityTagGroups && typeof settings.priorityTagGroups === 'object') {
      tenantPriorityGroupsCache.set(tenantId, settings.priorityTagGroups);
    }
    if (Array.isArray(settings.genericWords)) {
      tenantGenericWordsCache.set(tenantId, new Set(settings.genericWords.map((w: string) => String(w).toLowerCase())));
    }
  } catch {}
}

function getPriorityGroupsForTenant(tenantId: string): Record<string, string[]> {
  return tenantPriorityGroupsCache.get(tenantId) || DEFAULT_PRIORITY_TAG_GROUPS;
}

function getGenericWordsForTenant(tenantId: string): Set<string> {
  return tenantGenericWordsCache.get(tenantId) || DEFAULT_DOMAIN_GENERIC_WORDS;
}

// Backwards-compat alias (kode lama pakai nama ini)
const PRIORITY_TAG_GROUPS = DEFAULT_PRIORITY_TAG_GROUPS;
const DOMAIN_GENERIC_WORDS = DEFAULT_DOMAIN_GENERIC_WORDS;

const hasAnyTag = (tags: string[] | undefined, group: string[]): boolean =>
  !!tags && tags.some((t) => group.includes(t.toLowerCase()));

export class FewShotExemplarBank {
  /**
   * Mengambil daftar seluruh exemplar untuk tenant (aktif & non-aktif).
   * forceRefresh = true memaksa baca ulang dari database (melewati cache).
   */
  public static async getAllExemplars(
    tenantId: string = DEFAULT_TENANT_ID,
    forceRefresh: boolean = false
  ): Promise<FewShotExemplar[]> {
    if (!forceRefresh) {
      const cached = tenantExemplarsCache.get(tenantId);
      if (cached) return cached; // [] juga valid (admin sengaja kosongkan)
    }

    try {
      const { prisma } = await import('../../db/client');
      const rows = await prisma.fewShotExemplar.findMany({
        where: { tenant_id: tenantId },
        orderBy: [{ sort_order: 'asc' }, { created_at: 'asc' }],
      });

      // AUTO-SEED NON-DESTRUKTIF: tabel kosong + tenant benar-benar baru
      // (belum ada riwayat kelola FEW_SHOT_* di audit_logs) → seed 7 default
      // SOP dengan UUID riil. Jika admin pernah mengelola bank lalu
      // mengosongkannya (ada riwayat audit / flag empty-state), hormati
      // kekosongan tersebut — JANGAN resurrect default sepihak.
      if (rows.length === 0 && !tenantEmptyStateCache.get(tenantId)) {
        let hasPriorActivity = false;
        try {
          const prior = await (prisma as any).auditLog?.findFirst?.({
            where: { tenant_id: tenantId, action: { startsWith: 'FEW_SHOT_' } },
          });
          hasPriorActivity = !!prior;
        } catch {
          hasPriorActivity = false;
        }
        if (!hasPriorActivity) {
          try {
            const seeded: FewShotExemplar[] = [];
            for (let i = 0; i < DEFAULT_FEW_SHOT_EXEMPLARS.length; i++) {
              const d = DEFAULT_FEW_SHOT_EXEMPLARS[i];
              const created = await prisma.fewShotExemplar.create({
                data: {
                  tenant_id: tenantId,
                  scenario: d.scenario,
                  customer_message: d.customerMessage,
                  ideal_response: d.idealResponse,
                  tags: d.tags,
                  is_active: true,
                  sort_order: i + 1,
                },
              });
              seeded.push(mapRowToExemplar(created));
            }
            tenantExemplarsCache.set(tenantId, seeded);
            tenantEmptyStateCache.set(tenantId, false);
            return seeded;
          } catch (seedErr: any) {
            console.warn('[FEW SHOT BANK] Auto-seed gagal, fallback in-memory:', seedErr.message);
          }
        }
      }

      const mapped = rows.map(mapRowToExemplar);
      tenantExemplarsCache.set(tenantId, mapped);
      tenantEmptyStateCache.set(tenantId, mapped.length === 0);
      return mapped;
    } catch (err: any) {
      // DB offline: fallback diam-diam. Jika cache per-tenant sudah ada, pakai itu.
      const cached = tenantExemplarsCache.get(tenantId);
      if (cached) return cached;
      // Tanpa DB & tanpa cache: jangan resurrect default bila tenant pernah
      // ditandai sengaja kosong; selain itu fallback ke default exemplars.
      if (tenantEmptyStateCache.get(tenantId)) return [];
      const defaults = DEFAULT_FEW_SHOT_EXEMPLARS.map((d) => ({ ...d, tenantId }));
      tenantExemplarsCache.set(tenantId, defaults);
      return defaults;
    }
  }

  /**
   * Menambahkan exemplar baru ke DB dan memperbarui cache.
   */
  public static async createExemplar(
    data: {
      scenario: string;
      customerMessage: string;
      idealResponse: string;
      tags: string[];
      isActive?: boolean;
    },
    tenantId: string = DEFAULT_TENANT_ID
  ): Promise<FewShotExemplar> {
    const isActive = data.isActive ?? true;
    const clean = {
      scenario: (data.scenario || '').trim(),
      customerMessage: (data.customerMessage || '').trim(),
      idealResponse: (data.idealResponse || '').trim(),
      tags: Array.isArray(data.tags)
        ? data.tags.map((t) => String(t).trim().toLowerCase()).filter(Boolean)
        : [],
    };
    let createdRow: any = null;

    try {
      const { prisma } = await import('../../db/client');
      const currentList = await this.getAllExemplars(tenantId, true);
      const nextSortOrder = currentList.length + 1;
      createdRow = await prisma.fewShotExemplar.create({
        data: {
          tenant_id: tenantId,
          scenario: clean.scenario,
          customer_message: clean.customerMessage,
          ideal_response: clean.idealResponse,
          tags: clean.tags,
          is_active: isActive,
          sort_order: nextSortOrder,
        },
      });
    } catch (err: any) {
      console.warn('[FEW SHOT BANK] DB create failed, updating in-memory only:', err.message);
    }

    const newExemplar: FewShotExemplar = createdRow
      ? mapRowToExemplar(createdRow)
      : {
          id: `ex_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
          tenantId,
          scenario: clean.scenario,
          customerMessage: clean.customerMessage,
          idealResponse: clean.idealResponse,
          tags: clean.tags,
          isActive,
          sortOrder: (tenantExemplarsCache.get(tenantId) || []).length + 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        };

    const current = tenantExemplarsCache.get(tenantId) || [];
    current.push(newExemplar);
    tenantExemplarsCache.set(tenantId, current);
    tenantEmptyStateCache.set(tenantId, false);

    return newExemplar;
  }

  /**
   * Mengupdate exemplar di DB dan cache.
   */
  public static async updateExemplar(
    id: string,
    data: Partial<{
      scenario: string;
      customerMessage: string;
      idealResponse: string;
      tags: string[];
      isActive: boolean;
      sortOrder: number;
    }>,
    tenantId: string = DEFAULT_TENANT_ID
  ): Promise<FewShotExemplar | null> {
    let updatedRow: any = null;
    try {
      const { prisma } = await import('../../db/client');
      updatedRow = await prisma.fewShotExemplar.update({
        where: { id },
        data: {
          ...(data.scenario !== undefined && { scenario: String(data.scenario).trim() }),
          ...(data.customerMessage !== undefined && { customer_message: String(data.customerMessage).trim() }),
          ...(data.idealResponse !== undefined && { ideal_response: String(data.idealResponse).trim() }),
          ...(data.tags !== undefined && {
            tags: (Array.isArray(data.tags) ? data.tags : [])
              .map((t) => String(t).trim().toLowerCase())
              .filter(Boolean),
          }),
          ...(data.isActive !== undefined && { is_active: data.isActive }),
          ...(data.sortOrder !== undefined && { sort_order: data.sortOrder }),
        },
      });
    } catch (err: any) {
      console.warn('[FEW SHOT BANK] DB update failed, updating in-memory only:', err.message);
    }

    const current = await this.getAllExemplars(tenantId, true);
    const index = current.findIndex((c) => c.id === id);
    if (index === -1) return null;

    const updated: FewShotExemplar = updatedRow
      ? mapRowToExemplar(updatedRow)
      : {
          ...current[index],
          ...(data.scenario !== undefined && { scenario: String(data.scenario).trim() }),
          ...(data.customerMessage !== undefined && { customerMessage: String(data.customerMessage).trim() }),
          ...(data.idealResponse !== undefined && { idealResponse: String(data.idealResponse).trim() }),
          ...(data.tags !== undefined && {
            tags: (Array.isArray(data.tags) ? data.tags : [])
              .map((t) => String(t).trim().toLowerCase())
              .filter(Boolean),
          }),
          ...(data.isActive !== undefined && { isActive: data.isActive }),
          ...(data.sortOrder !== undefined && { sortOrder: data.sortOrder }),
          updatedAt: new Date(),
        };

    current[index] = updated;
    tenantExemplarsCache.set(tenantId, current);
    tenantEmptyStateCache.set(tenantId, current.length === 0);
    return updated;
  }

  /**
   * Menghapus exemplar dari DB dan cache.
   */
  public static async deleteExemplar(id: string, tenantId: string = DEFAULT_TENANT_ID): Promise<boolean> {
    try {
      const { prisma } = await import('../../db/client');
      await prisma.fewShotExemplar.deleteMany({
        where: { id, tenant_id: tenantId },
      });
    } catch (err: any) {
      console.warn('[FEW SHOT BANK] DB delete failed, updating in-memory only:', err.message);
    }

    const current = await this.getAllExemplars(tenantId, true);
    const filtered = current.filter((c) => c.id !== id);
    tenantExemplarsCache.set(tenantId, filtered);
    tenantEmptyStateCache.set(tenantId, filtered.length === 0);
    return true;
  }

  /**
   * Mengubah urutan prioritas exemplar tenant.
   * orderedIds berisi id dalam urutan baru yang diinginkan (1..N).
   */
  public static async reorderExemplars(
    orderedIds: string[],
    tenantId: string = DEFAULT_TENANT_ID
  ): Promise<FewShotExemplar[]> {
    if (!Array.isArray(orderedIds) || orderedIds.length === 0) {
      return this.getAllExemplars(tenantId, true);
    }

    let dbOk = true;
    try {
      const { prisma } = await import('../../db/client');
      await prisma.$transaction(
        orderedIds.map((id, idx) =>
          prisma.fewShotExemplar.update({
            where: { id },
            data: { sort_order: idx + 1 },
          })
        )
      );
    } catch (err: any) {
      dbOk = false;
      console.warn('[FEW SHOT BANK] DB reorder failed, updating in-memory only:', err.message);
    }

    if (!dbOk) {
      // DB offline: tetap terapkan urutan baru pada cache in-memory
      // (paritas perilaku dengan create/update/delete).
      const current = await this.getAllExemplars(tenantId, true);
      const byId = new Map(current.map((e) => [e.id, e]));
      const reordered: FewShotExemplar[] = [];
      for (const id of orderedIds) {
        const ex = byId.get(id);
        if (ex) {
          reordered.push({ ...ex, sortOrder: reordered.length + 1 });
          byId.delete(id);
        }
      }
      // Sisa yang tidak disebutkan dipertahankan di urutan akhir.
      for (const ex of current) {
        if (byId.has(ex.id)) {
          reordered.push({ ...ex, sortOrder: reordered.length + 1 });
        }
      }
      tenantExemplarsCache.set(tenantId, reordered);
      return reordered;
    }

    // DB sukses: sinkronkan cache dengan urutan baru.
    return this.getAllExemplars(tenantId, true);
  }

  /**
   * Memulihkan contoh SOP klinik bawaan secara ADDITIVE / non-destruktif.
   * - Exemplar sistem yang sudah ada (dicocokkan via teks scenario kanonik)
   *   diperbarui isinya + diaktifkan kembali, ID & sort_order dipertahankan.
   * - Exemplar sistem yang hilang dibuat ulang di urutan akhir.
   * - Exemplar KUSTOM buatan admin TIDAK PERNAH dihapus/diubah.
   * Mengembalikan record dengan ID ASLI dari database (UUID), bukan id
   * statis DEFAULT_FEW_SHOT_EXEMPLARS — agar Edit/Delete pasca-pulihkan
   * tidak menghasilkan 404 karena ID mismatch.
   */
  public static async resetToDefaults(tenantId: string = DEFAULT_TENANT_ID): Promise<FewShotExemplar[]> {
    try {
      const { prisma } = await import('../../db/client');
      const existing = await prisma.fewShotExemplar.findMany({
        where: { tenant_id: tenantId },
      });
      const byScenario = new Map((existing || []).map((r: any) => [r.scenario, r]));
      let maxSort = (existing || []).reduce((m: number, r: any) => Math.max(m, r.sort_order ?? 0), 0);

      for (let i = 0; i < DEFAULT_FEW_SHOT_EXEMPLARS.length; i++) {
        const d = DEFAULT_FEW_SHOT_EXEMPLARS[i];
        const found = byScenario.get(d.scenario);
        if (found) {
          await prisma.fewShotExemplar.update({
            where: { id: (found as any).id },
            data: {
              customer_message: d.customerMessage,
              ideal_response: d.idealResponse,
              tags: d.tags,
              is_active: true,
            },
          });
        } else {
          maxSort += 1;
          await prisma.fewShotExemplar.create({
            data: {
              tenant_id: tenantId,
              scenario: d.scenario,
              customer_message: d.customerMessage,
              ideal_response: d.idealResponse,
              tags: d.tags,
              is_active: true,
              sort_order: maxSort,
            },
          });
        }
      }
    } catch (err: any) {
      console.warn('[FEW SHOT BANK] DB restore gagal, merge in-memory saja:', err.message);
      // DB offline: merge non-destruktif pada cache in-memory.
      const current =
        tenantExemplarsCache.get(tenantId) ||
        DEFAULT_FEW_SHOT_EXEMPLARS.map((d) => ({ ...d, tags: [...d.tags], tenantId }));
      const merged = [...current];
      let maxSort = merged.reduce((m, e) => Math.max(m, e.sortOrder ?? 0), 0);
      for (const d of DEFAULT_FEW_SHOT_EXEMPLARS) {
        const idx = merged.findIndex((e) => e.scenario === d.scenario);
        if (idx >= 0) {
          merged[idx] = {
            ...merged[idx],
            customerMessage: d.customerMessage,
            idealResponse: d.idealResponse,
            tags: [...d.tags],
            isActive: true,
            updatedAt: new Date(),
          };
        } else {
          maxSort += 1;
          merged.push({
            ...d,
            tags: [...d.tags],
            tenantId,
            sortOrder: maxSort,
            createdAt: new Date(),
            updatedAt: new Date(),
          });
        }
      }
      tenantExemplarsCache.set(tenantId, merged);
      tenantEmptyStateCache.set(tenantId, merged.length === 0);
      return merged;
    }

    // DB sukses: baca ulang agar ID riil + contoh kustom ikut kembali.
    const refreshed = await this.getAllExemplars(tenantId, true);
    tenantEmptyStateCache.set(tenantId, refreshed.length === 0);
    return refreshed;
  }

  /**
   * Memilih 1-2 contoh percakapan ideal yang paling relevan dengan pesan dan intent customer saat ini.
   */
  public static selectRelevantExemplars(
    extraction: ExtractedEntities,
    slate?: CustomerSlate,
    customerInput?: string,
    tenantId: string = DEFAULT_TENANT_ID
  ): FewShotExemplar[] {
    const inputLower = (customerInput || '').toLowerCase();
    const cached = tenantExemplarsCache.get(tenantId) || DEFAULT_FEW_SHOT_EXEMPLARS;
    const activeExemplars = cached.filter((e) => e.isActive !== false);
    const priorityGroups = getPriorityGroupsForTenant(tenantId);
    const genericWords = getGenericWordsForTenant(tenantId);

    const scored: Array<{ exemplar: FewShotExemplar; score: number }> = [];

    for (const ex of activeExemplars) {
      let score = 0;
      let genericOnlyScore = 0;
      const exTags = (ex.tags || []).map((t) => t.toLowerCase());

      // 1. Cocokkan dengan tags — word boundary (hindari false positive
      //    sub-kata seperti "flu" di dalam "fluktuasi").
      for (const tag of exTags) {
        if (inputLower && isWordTagMatch(inputLower, tag)) {
          if (genericWords.has(tag)) genericOnlyScore += 3;
          else score += 3;
        }
        if (extraction.intents.some((i) => i === tag || i.includes(tag))) score += 4;
        if (extraction.symptoms.some((s) => s === tag || s.includes(tag))) score += 4;
      }

      // 2. Prioritaskan jadwal jika ada mention hari/jadwal — berbasis TAG,
      //    sehingga exemplar kustom bertag jadwal ikut diprioritaskan.
      const hasScheduleTag = hasAnyTag(exTags, priorityGroups.schedule);
      if (hasScheduleTag && (extraction.intents.includes('ask_schedule') || Boolean(extraction.preferredDateText))) {
        score += 5;
      }

      // 3. Prioritaskan harga jika ada intent ask_price.
      if (hasAnyTag(exTags, priorityGroups.price) && extraction.intents.includes('ask_price')) {
        score += 5;
      }

      // 3b. Prioritaskan lokasi/ongkir HANYA bila ada bukti di sisi input
      // (cocok kata-tag lokasi atau intent alamat) — tanpa bukti input, input netral
      // seperti "halo"/"oke" harus menghasilkan [] (tanpa suntikan salah konteks).
      const hasLocationSignal =
        hasAnyTag(exTags, priorityGroups.location) &&
        (exTags.some((t) => inputLower && isWordTagMatch(inputLower, t)) ||
          extraction.intents.includes('provide_location') ||
          extraction.intents.includes('supplement_address'));
      if (hasLocationSignal) {
        score += 5;
      }

      // 4. Prioritaskan keluhan jika ada symptoms.
      if (
        hasAnyTag(exTags, priorityGroups.symptom) &&
        (extraction.symptoms.length > 0 || extraction.intents.includes('consult_symptom'))
      ) {
        score += 5;
      }

      // 5. Prioritaskan follow-up jika ongkir sudah pernah terkirim.
      if (
        hasAnyTag(exTags, priorityGroups.treatment_continuation) &&
        slate?.isLocationConfirmed &&
        !slate.selectedTreatmentName
      ) {
        score += 2;
      }

      // 6. Filter stopword domain: poin dari kata generik (bayi/moms/spa/anak/ibu)
      // hanya dihitung bila ada poin substantif lain — cegah false positive.
      scored.push({ exemplar: ex, score: score > 0 ? score + genericOnlyScore : 0 });
    }

    // Urutkan skor tertinggi dan ambil maksimal 2 contoh
    scored.sort((a, b) => b.score - a.score);
    const top = scored.filter((s) => s.score > 0).slice(0, 2);

    // Tanpa topik relevan: kembalikan [] — JANGAN paksa exemplar pertama (blind fallback
    // menyuntik contoh salah konteks, misal batuk/pilek untuk pesan alamat).
    // V3 mempertahankan prompt dasar statis; Call 2 tidak menyuntik blok palsu;
    // Inspector Sandbox menampilkan 0 exemplar secara jujur.
    if (top.length === 0) {
      return [];
    }

    return top.map((t) => t.exemplar);
  }

  /**
   * Format exemplar menjadi blok teks ramah prompt.
   */
  public static formatExemplarsForPrompt(exemplars: FewShotExemplar[]): string {
    if (!exemplars || exemplars.length === 0) return '';

    const formatted = exemplars
      .map(
        (e, idx) =>
          `Contoh ${idx + 1} (${e.scenario}):\n` +
          `Pasien: "${e.customerMessage}"\n` +
          `Bidan Yusi: "${e.idealResponse}"`
      )
      .join('\n\n');

    return `CONTOH PERCAKAPAN IDEAL BIDAN YUSI (TIRU POLA DAN NADA BICARANYA):\n${formatted}`;
  }

  // ===== Hook eksklusif untuk unit test (deterministik, offline) =====
  /** Seed cache in-memory per tenant (hanya dipakai test). */
  public static __setCacheForTest(tenantId: string, exemplars: FewShotExemplar[]): void {
    tenantExemplarsCache.set(tenantId, exemplars);
    tenantEmptyStateCache.set(tenantId, exemplars.length === 0);
  }

  /** Bersihkan cache per tenant (hanya dipakai test). */
  public static __clearCacheForTest(tenantId: string): void {
    tenantExemplarsCache.delete(tenantId);
    tenantEmptyStateCache.delete(tenantId);
  }
}
