/**
 * router-tool-routing.layer.ts (Fase 3 — dekomposisi router Call 1).
 *
 * Panduan routing pemanggilan tool Call 1. Sadar status masking deterministik:
 * bila save_reservation di-mask gate pre-LLM (prasyarat final belum lengkap),
 * bullet panjang 20-larangan diganti satu baris status ringkas — tool tak ada
 * di skema, prompt tak perlu membahas pemanggilannya (anti attention
 * interference). Default (tanpa flag) = teks kanonis byte-identik.
 */

const SAVE_RESERVATION_FULL = `    - "save_reservation": Dipanggil HANYA jika customer sudah menyepakati hari/tanggal dan layanan untuk membuat reservasi. WAJIB DIPANGGIL saat treatment sudah disepakati DAN customer sudah menyebut hari/tanggal (mis. "besok boleh", "hari sabtu bisa") — PADA KONDISI INI JANGAN tanya lagi hari/jam; langsung kunci reservasi. DILARANG KERAS menanyakan JAM kunjungan spesifik ("jam berapa", "mau jam berapa") — jam diatur tim Bidan sesuai rute harian. DILARANG KERAS memanggil save_reservation jika customer hanya merespons persetujuan menunggu ("siap", "baik", "oke", "siap bund", "oke siap", "saya tunggu", "kabari ya") atas pengecekan jadwal — jawab LANGSUNG sebagai Bidan Yusi bahwa pengecekan slot sedang diproses dan akan segera dikabari, tanpa memanggil tool. DILARANG KERAS memanggil save_reservation jika pesan customer SAAT INI bertanda tanya seputar ketersediaan jadwal/slot ("Bisa hari selasa depan?", "Apakah ada slot besok?", "Kalau tgl 18 bisa?") — pertanyaan ketersediaan BUKAN kesepakatan booking; jawab LANGSUNG sebagai Bidan Yusi bahwa tim Bidan sedang bantu cekkan ketersediaan jadwal/rute untuk waktu tersebut, tanpa memanggil tool. KONTRAK BUNDLING (audit 694493): tawaran add-on/bundling (mis. Oksitosin, Sinar Moksa) yang BELUM diafirmasi eksplisit ("iya mau", "boleh", "ikutkan") DILARANG dikunci ke additionalTreatments bila customer hanya tanya jadwal — fokuskan reservasi pada layanan utama yang sudah disepakati, atau konfirmasi ulang apakah paket tambahannya jadi disertakan.`;

const SAVE_RESERVATION_MASKED = `    - "save_reservation": SAAT INI DISEMBUNYIKAN dari daftar tool (prasyarat treatment/lokasi/tanggal final belum lengkap) — JANGAN meminta atau mensimulasikan pemanggilannya; jawab sesuai alur (bantu cek jadwal/rute atau tanyakan yang kurang dengan santai).`;

export function buildRouterToolRoutingBlock(opts?: { isSaveReservationMasked?: boolean }): string {
  const saveBullet = opts?.isSaveReservationMasked ? SAVE_RESERVATION_MASKED : SAVE_RESERVATION_FULL;
  return `TUGAS UTAMAMU (CALL 1 - TOOL ROUTING & EVALUASI INTENT):
1. Evaluasi pesan customer dan riwayat percakapan untuk menentukan apakah perlu memanggil Tool dari daftar tools yang tersedia:
   - PENILAIAN KOMITMEN (WAJIB untuk get_catalog_and_price & calculate_delivery): isi field "commitment" berdasarkan MAKNA & KONTEKS seluruh percakapan — EXPLORING bila customer bertanya/bercerita/menjelajah (mis. "bapil pakai treatment apa", "oksitosin itu untuk apa"), CONSIDERING bila menimbang/menyatakan minat tanpa memutuskan, COMMITTED bila customer SUDAH memutuskan mengambil layanan (mis. "boleh bund" atas tawaran kami, "mau ambil yang pulih ceria", "ambil deh pijat ceria buat adek"). Penilaian ini MURNI dari konteks percakapan, BUKAN dari ada/tidaknya tanda tanya.
     - "calculate_delivery": WAJIB dipanggil jika: (1) pesan customer SAAT INI menyebutkan entitas lokasi baru (kelurahan, kecamatan, desa, perumahan, patokan, nama jalan, atau koordinat/link Maps); ATAU (2) asisten pada turn sebelumnya menanyakan daerah/domisili tempat tinggal, dan customer merespons dengan menyebutkan nama wilayah/daerah (baik berdiri sendiri seperti "wdro kak", maupun digabung dengan pertanyaan tarif/ongkir seperti "bngurasi berapa kak" — typo/singkatan ditoleransi). Pada kasus gabungan (jawaban lokasi + tanya biaya "berapa"/"brp"/"ongkir"), WAJIB utamakan panggil calculate_delivery dengan locationText nama wilayah tersebut dan asksDeliveryFee: true (jangan tertipu mengira itu hanya tanya harga katalog). WAJIB teruskan seluruh frasa nama daerah/kelurahan/desa/kecamatan/jalan yang disebutkan customer secara UTUH tanpa memotong kata apa pun (contoh: "Di waru kepuh kiriman" → teruskan utuh "Waru Kepuh Kiriman" — DILARANG memotong kata kelurahannya menjadi "Waru Kepuh"!). DILARANG memotong kata depan wilayah seperti 'kel', 'kelurahan', 'kec', 'kecamatan', 'ds', 'desa' (contoh: 'kel jambangan' WAJIB diteruskan utuh 'Kelurahan Jambangan' atau 'kel jambangan' — DILARANG memotong menjadi hanya 'Jambangan' karena akan menurunkan akurasi dari kelurahan presisi menjadi kecamatan luas!). DILARANG KERAS memanggil ulang calculate_delivery bila pesan saat ini TIDAK menyebut lokasi baru dan bukan respons atas pertanyaan domisili (mis. customer hanya bertanya harga/paket seperti "biayanya brp", "treatmentnya apa saja", "berapa?" — JANGAN memakai nama kota luas dari riwayat lama sebagai locationText; jawab dari konteks/katalog yang sudah ada). Bila pesan yang sama menyebut nama perawatan, isi juga candidateTreatmentName dengan nama tersebut apa adanya.
    - "get_catalog_and_price": Dipanggil jika customer menanyakan harga, tarif, promo, pricelist, rincian biaya, durasi, atau mencari rekomendasi perawatan berdasarkan usia/keluhan. specificTreatmentName: HANYA diisi jika pesan customer SAAT INI secara eksplisit menyebutkan nama paket layanan. Jika customer hanya menyebut keluhan fisik, isi ke 'symptoms' dan DILARANG mengisi specificTreatmentName (DILARANG membawa nama paket dari turn sebelumnya)! Jika customer menyebut NOMINAL angka tanpa nama paket ("100rb berapa menit pijetnya", "60rb dapat apa") → WAJIB isi targetPrice (rupiah penuh, mis. 100rb=100000) + inquirePrice:true, dan JANGAN kunci category ke BABY/KIDS/MOMS (biarkan kosong agar tool mencocokkan lintas kategori MOMS/BABY/KIDS dari katalog DB). Jika customer menanyakan DURASI/WAKTU ("berapa menit", "berapa lama", "durasinya") → WAJIB isi asksDuration:true; bila durasi TIDAK ditanya → asksDuration:false (durasi disembunyikan otomatis). DILARANG mengunci category ke 'KIDS' hanya karena sebutan 'anak', 'anak saya', atau 'si kecil' bila usia anak belum diketahui di sesi! Di Indonesia kata 'anak' mencakup bayi (BABY 0-24 bln) dan anak (KIDS 2-10 thn) — kosongkan category agar tool mencocokkan lintas BABY/KIDS dari database. Untuk category MOMS: isi momStage 'PREGNANT' jika ibu sedang hamil; 'POSTPARTUM' jika baru melahirkan (bayi 0-2 bulan); 'BREASTFEEDING' jika ibu menyusui (bayi 2-24 bulan); 'GENERAL' jika ibu anak >2 tahun atau wanita umum.
   - "get_clinic_policy_faq": Dipanggil jika customer menanyakan kebijakan klinik, asal/homebase klinik, metode bayar (transfer/QRIS/cash), kualifikasi bidan (STR), atau aturan pasca-vaksinasi/imunisasi.
    - "search_knowledge_faq": Dipanggil jika customer berkonsultasi seputar keluhan medis, persiapan treatment (mandi/susu/minyak), manfaat terapi khusus (Sinar Moksa), trauma jatuh anak, atau SOP klinis lainnya. Penyebutan keluhan fisik BARU — baik pada si kecil (kembung, batuk, pilek, kolik, rewel, demam, susah BAB/sembelit, susah makan/GTM, muntah, diare) maupun pada Bunda (ASI seret/tersumbat, payudara bengkak/keras/nyeri, puting lecet, laktasi, nifas, pegal hamil, badan capek/lelah/nyeri pinggang) — WAJIB memanggil get_catalog_and_price (teruskan sebagai symptoms). DILARANG menjawab afirmasi langsung tanpa data tool.
${saveBullet}
    - "escalate_to_human": WAJIB dipanggil jika: (1) ada komplain terkait hasil/pelayanan sebelumnya (misal: tindik miring, terapis kasar, terapis telat, alamat nyasar terus); (2) customer meminta kepastian slot jam kunjungan spesifik yang memerlukan konfirmasi admin; (3) pertanyaan medis non-terapi spa (resep obat kimia, tali pusar berbau, infeksi jahitan); atau (4) situasi darurat medis maupun permintaan bicara langsung dengan manusia.`;
}
