import { GoldenScenario } from '../types';

export const acknowledgementScenarios: GoldenScenario[] = [
  { id: 'ACK-01', category: 'acknowledgement', weight: 4, description: 'Oke bund — lanjutkan tanpa ulang salam', turns: [{ turn: 1, input: 'Halo, bayi 2 bulan pilek', mustContain: ['Pulih'] }, { turn: 2, input: 'Oke bund', mustNotContain: ['Halo Bunda!','Perkenalkan saya Bidan Yusi'], noUnjustifiedRsqr: true }] },
  { id: 'ACK-02', category: 'acknowledgement', weight: 2, description: 'Boleh onty bid — hangat', turns: [{ turn: 1, input: 'Info pijat bayi dong', mustContain: ['Bunda'] }, { turn: 2, input: 'Boleh onty bid 🥰', mustNotContain: ['Halo Bunda!'], noSilentDrop: true }] },
  { id: 'ACK-03', category: 'acknowledgement', weight: 3, description: 'Iya kak setelah tawar jadwal', turns: [{ turn: 1, input: 'Besok bisa pijat?', mustContain: ['cekkan'] }, { turn: 2, input: 'Iya kak', mustNotContain: ['Halo Bunda!'], noUnjustifiedRsqr: true }] },
  { id: 'ACK-04', category: 'acknowledgement', weight: 3, description: 'Hanya emoji — anti error len<5', turns: [{ turn: 1, input: 'Mau pijat bayi', mustContain: ['Bunda'] }, { turn: 2, input: '🥰', noSilentDrop: true, mustNotContain: ['error'] }] },
  { id: 'ACK-05', category: 'acknowledgement', weight: 3, description: 'Siappp setelah ongkir — jangan ulang tarif', turns: [{ turn: 1, input: 'Rumah di Rungkut', mustContain: ['ongkir'] }, { turn: 2, input: 'Siappp', mustNotContain: ['Rp','ongkir'], noUnjustifiedRsqr: true }] },
  { id: 'ACK-06', category: 'acknowledgement', weight: 2, description: 'Makasih infonya bubid — penutup santun', turns: [{ turn: 1, input: 'Pijat bayi berapa?', mustContain: ['Rp'] }, { turn: 2, input: 'Makasihh infonya bubid', mustNotContain: ['Halo Bunda!'] }] },
  { id: 'ACK-07', category: 'acknowledgement', weight: 1, description: 'Baik kak maaf baru respon — lanjutkan lama', turns: [{ turn: 1, input: 'Bayi 6 bulan batuk', mustContain: ['batuk'] }, { turn: 2, input: 'Baik kak, maaf baru respon', mustNotContain: ['Halo Bunda!'] }] },
  { id: 'ACK-08', category: 'acknowledgement', weight: 2, description: 'Boleh kak konfirmasi', turns: [{ turn: 1, input: 'Mau pijat laktasi', mustContain: ['Bunda'] }, { turn: 2, input: 'Boleh kak', noSilentDrop: true }] },
  { id: 'ACK-09', category: 'acknowledgement', weight: 2, description: 'Iya betul konfirmasi usia', turns: [{ turn: 1, input: 'Anak 1 tahun mau pijat', mustContain: ['Bunda'] }, { turn: 2, input: 'Iya betul', mustNotContain: ['berapa usia'] }] },
  { id: 'ACK-10', category: 'acknowledgement', weight: 1, description: 'nggeh bu bidan — Jawa sopan', turns: [{ turn: 1, input: 'Pijat bayi bisa besok?', mustContain: ['cekkan'] }, { turn: 2, input: 'nggeh bu bidan', noSilentDrop: true }] },
  { id: 'ACK-11', category: 'acknowledgement', weight: 1, description: 'bentar nggeh bu bidan — menunggu tanpa spam', turns: [{ turn: 1, input: 'Mau booking pijat bayi', mustContain: ['Bunda'] }, { turn: 2, input: 'bentar nggeh bu bidan', mustNotContain: ['Halo Bunda!'] }] },
  { id: 'ACK-12', category: 'acknowledgement', weight: 1, description: 'Oke saya diskusikan dulu — tanpa paksa booking', turns: [{ turn: 1, input: 'Pijat bayi berapa?', mustContain: ['Rp'] }, { turn: 2, input: 'Oke saya diskusikan dulu dengan suami', mustNotContain: ['Halo Bunda!','paksa'] }] },
  { id: 'ACK-13', category: 'acknowledgement', weight: 1, description: 'Halo kak di tengah percakapan — jangan greeting panjang lagi', turns: [{ turn: 1, input: 'Bayi pilek', mustContain: ['pilek'] }, { turn: 2, input: 'Halo kak', mustNotContain: ['Perkenalkan saya Bidan Yusi'] }] },
];
