import { GoldenScenario } from '../types';

export const bookingScenarios: GoldenScenario[] = [
  { id: 'BOOK-01', category: 'booking', weight: 3, description: 'Typo besok — bsk apa tdk bs d carikan waktu', turns: [{ turn: 1, input: 'bsk apa tdk bs d carikan waktu', expectedIntents: ['ask_schedule'], mustContain: ['Bunda'], mustNotContain: ['Tentu bisa'] }] },
  { id: 'BOOK-02', category: 'booking', weight: 2, description: 'Slot weekend Sabtu/Minggu', turns: [{ turn: 1, input: 'Sabtu atau Minggu ini ada slot kosong?', expectedIntents: ['ask_schedule'], mustContain: ['cekkan'] }] },
  { id: 'BOOK-03', category: 'booking', weight: 3, description: 'Jam spesifik besok jam 10 — no false affirmation', turns: [{ turn: 1, input: 'bisa besok jam 10 pagi?', expectedIntents: ['ask_schedule'], mustContain: ['cekkan'], mustNotContain: ['Tentu bisa','Pasti bisa'] }] },
  { id: 'BOOK-04', category: 'booking', weight: 2, description: 'Same-day sekarang bisa?', turns: [{ turn: 1, input: 'sekarang kak bisa?', expectedIntents: ['ask_schedule'], mustContain: ['cekkan'] }] },
  { id: 'BOOK-05', category: 'booking', weight: 3, description: 'Form booking lengkap', turns: [{ turn: 1, input: 'Nama Bunda: Sari\nAlamat: Waru\nNo Hp: 08123456789\nNama Bayi: Adek\nUsia: 2 bulan\nTreatment: Pijat Bayi Ceria\nHari dan tanggal: besok', expectedIntents: ['request_booking'], mustContain: ['Bunda'], noSilentDrop: true }] },
  { id: 'BOOK-06', category: 'booking', weight: 1, description: 'Form booking parsial', turns: [{ turn: 1, input: 'Nama Bunda: Sari\nNama Bayi: Adek\nTreatment: Pijat Bayi Ceria', expectedIntents: ['request_booking'], mustContain: ['Bunda'] }] },
  { id: 'BOOK-07', category: 'booking', weight: 1, description: 'Koreksi jadwal setelah booking', turns: [{ turn: 1, input: 'Nama Bunda: Sari\nAlamat: Waru\nTreatment: Pijat Bayi Ceria\nHari: Sabtu', mustContain: ['Bunda'] }, { turn: 2, input: 'Maaf ganti jadi Minggu ya', expectedIntents: ['ask_schedule'], mustContain: ['Bunda'] }] },
  { id: 'BOOK-08', category: 'booking', weight: 2, description: 'Jam operasional klinik', turns: [{ turn: 1, input: 'buka sampai jam berapa?', expectedIntents: ['chitchat'], mustContain: ['08.00','17.00'], noSilentDrop: true }] },
  { id: 'BOOK-09', category: 'booking', weight: 1, description: 'Permintaan di luar jam kerja jam 8 malam', turns: [{ turn: 1, input: 'Bisa jam 8 malam?', expectedIntents: ['ask_schedule'], mustContain: ['08.00','17.00'], mustNotContain: ['Tentu bisa'] }] },
  { id: 'BOOK-10', category: 'booking', weight: 1, description: 'Booking kembar 2 anak sekaligus', turns: [{ turn: 1, input: 'Mau booking untuk anak kembar usia 6 bulan dan 1 tahun, dua-duanya pijat', expectedIntents: ['provide_age'], mustContain: ['Bunda'] }] },
  { id: 'BOOK-11', category: 'booking', weight: 1, description: 'Kepastian kedatangan terapis sampai dimana', turns: [{ turn: 1, input: 'sampai dimana ya kak terapisnya?', expectedIntents: ['chitchat'], mustContain: ['Bunda'] }] },
  { id: 'BOOK-12', category: 'booking', weight: 2, description: 'Konfirmasi pembayaran ShopeePay/QRIS', turns: [{ turn: 1, input: 'Bayar bisa ShopeePay atau QRIS?', expectedIntents: ['chitchat'], mustContain: ['QRIS','Transfer'], noSilentDrop: true }] },
];
